apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-default
spec:
  profile: default
  values:
    global:
      mtls:
        auto: true
    kiali:
      createDemoSecret: true
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        hpaSpec:
          maxReplicas: 3
          minReplicas: 1
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
