name: update-istio

on:
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
      - master

jobs:
  check-istio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Helm
        uses: ./.github/actions/helm
      - name: Update dependencies
        run: |
          make latest-istio
          git --no-pager diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Update Istio
          title: Update Istio
          body: |
            Istio operator updates
          branch: update-istio
