name: update-istio

on:
  schedule:
    - cron:  '0 8 */1 * *'

jobs:
  check-istio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Helm
        uses: ./.github/actions/helm
      - name: Check Istio version
        id: check
        run: |
          curl -sL https://istio.io/downloadIstio | sh -
          ISTIO_DIR=$(find . -name 'istio-*' -type d -maxdepth 1 -print | head -n1)
          ISTIO_VER=${ISTIO_DIR##./istio-}

          echo "Build manifests for ${ISTIO_VER} in dir ${ISTIO_DIR}"
          helm template ${ISTIO_DIR}/install/kubernetes/operator/charts/istio-operator/ \
          --set hub=docker.io/istio \
          --set tag=${ISTIO_VER} \
          --set operatorNamespace=istio-operator \
          --set istioNamespace=istio-system  > ./istio/operator/manifests.yaml

          rm -rf ${ISTIO_DIR}

          if [[ $(git diff --stat) != '' ]]; then
            echo ::set-output name=version::${ISTIO_VER}
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        if: steps.check.outputs.version
        with:
          commit-message: Update Istio to ${{ steps.check.outputs.version }}
          title: Update Istio to ${{ steps.check.outputs.version }}
          body: |
            Istio operator v${{ steps.check.outputs.version }}
          branch: update-istio
